# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'img/posts'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'inner' }
      - { label: 'Position', name: 'position', widget: 'select', options: ["left", "right"] }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Categories', name: 'categories', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'string' }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image', choose_url: true, default: "/img/posts/default_image.jpg" }
      - { label: 'Project Link', name: 'project_link', widget: 'string' }
      - { label: 'Button Icon', name: 'button_icon', widget: 'string' }
      - { label: 'Button Text', name: 'button_text', widget: 'string' }
      - { label: 'Lead Text', name: 'lead_text', widget: 'text' }
      - { label: 'Status', name: 'status', widget: 'select', options: ["publish", "draft"] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    create: true
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'full' }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'About' }
          - { label: 'Permalink', name: 'permalink', widget: 'hidden', default: '/about/' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: '404 Page'
        name: '404'
        file: '404.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'full' }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'About' }
          - { label: 'Permalink', name: 'permalink', widget: 'hidden', default: '/404.html' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Navigation'
        name: 'navigation'
        file: '_data/navigation.yml'
        fields:
          - label: 'Navigation Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: url, widget: string }
      - label: 'Settings'
        name: 'settings'
        create: false
        file: '_data/settings.yml'
        fields:
          - { label: Footer Text, name: footer_text, widget: string }
          - { label: Admin Name, name: admin_name, widget: string }
          - { label: Google Analytic, name: google_analytics, widget: string }
          - { label: Enable Contact?, name: enable_contact, widget: "boolean", default: true }
          - { label: Enable Navigation?, name: enable_nav, widget: "boolean", default: true }
      - label: 'Socials'
        name: 'socmed'
        create: true
        file: '_data/socmed.yml'
        fields:
          - label: 'Social Items'
            name: 'socials'
            widget: 'list'
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Type, name: type, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Icon, name: icon, widget: string }